name: Super-Linter

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: super-linter/super-linter@v8.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
